version: '2'
services:
  server:
    environment:
      - 'POSTGRES_HOST=postgres'
      - 'POSTGRES_PORT=5432'
      - 'PORT=7070'
      - 'DB_ENV=prod'
    image: 'clover89/tictactoe:${GIT_COMMIT}'
    ports:
      - '7070:7070'
      - '5432:5432'   # This port had to be added for our app to work.
    links:
      - 'postgres'
  postgres:
    image: 'postgres'
    environment:
      - 'POSTGRES_PASSWORD=mysecretpassword'
      - 'POSTGRES_USER=postgres'
    expose:
      - '5432'
